# Run with ansible-playbook aio.yml -vvv --private-key=/root/lwade2.pem -u ec2-user -s
- name: Stage instance(s)
  hosts: local
  connection: local
  user: root
  sudo: False
  gather_facts: False

  vars:
      keypair: lwade2
      instance_type: m1.small
      security_group: lwade
      image: ami-8b485bff 

  tasks:
    - name: Launch instance 
      local_action: ec2 keypair=$keypair group=$security_group instance_type=$instance_type image=$image wait=true region=eu-west-1 
      register: ec2
     
    - name: Add new instance to host group
      local_action: add_host hostname=${item.public_ip} groupname=launched 
      with_items: ${ec2.instances}

    - name: Wait for SSH to come up
      local_action: wait_for host=${item.public_dns_name} port=22 delay=60 timeout=320 state=started
      with_items: ${ec2.instances}

    - name: Add the instance to my LB
      local_action: ec2_elb instance_id=${item.id} state=present ec2_elbs=lwadeelb
      with_items: ${ec2.instances}

- name: Configure instance(s)
  hosts: launched
  gather_facts: True
     
  handlers:
    - name: restart apache 
      action: service name=httpd state=restarted
 
  tasks:
    - name: Ensure NTP is up and running
      action: service name=ntpd state=started

    - name: Install Apache
      action: yum name=httpd state=latest
      notify: restart apache

    - name: Copy index.html
      action: copy src=files/index.html dest=/var/www/html/index.html owner=root group=root
      notify: restart apache
